name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --all-features
      - name: Copy binaries
        run: |
          mv target/armv7-unknown-linux-gnueabihf/release/line_count ./line_count
          mv target/armv7-unknown-linux-gnueabihf/debug/line_count ./line_count-debug
      - uses: actions/upload-artifact@v4
        with:
          name: line_count-armv7-unknown-linux-gnueabihf
          path: |
            line_count
            line_count-debug
  build_linux_x86:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        name: Build Release
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --release --all-features
      - uses: actions-rs/cargo@v1
        name: Build Debug
        with:
          use-cross: true
          command: build
          args: --target x86_64-unknown-linux-gnu --all-features
      - name: Copy binaries
        run: |
          mv target/x86_64-unknown-linux-gnu/release/line_count ./line_count
          mv target/x86_64-unknown-linux-gnu/debug/line_count ./line_count-debug
      - uses: actions/upload-artifact@v4
        with:
          name: line_count-x86_64-unknown-linux-gnu
          path: |
            line_count
            line_count-debug
